defaults:
    - _self_
    - env: bin_pack  # [bin_pack]

agent: factor_exe  # [random, pd, factor_exe]

seed: 0

logger:
    type: neptune  # [neptune, tensorboard, terminal]
    save_checkpoint: false  # [false, true]
    name: ${agent}_${env.name}
