name: bin_pack
kwargs:
    obs_num_ems: 40
    max_num_items: 15
    max_num_ems: 40
    split_num_same_items: 3


network:
    num_transformer_layers: 2
    transformer_num_heads: 8
    transformer_key_size: 16
    transformer_mlp_units: [512]
    factor_iterations: 3  # Only for FactorExeAgent
    factor_vocab_size: 200  # Only for FactorExeAgent

training:
    num_epochs: 500
    num_learner_steps_per_epoch: 100
    n_steps: 20
    total_batch_size: 512

evaluation:
    eval_total_batch_size: 8192
    greedy_eval_total_batch_size: 8192

agent:
    learning_rate: 3e-4
    reinforce_loss_coeff: 0.1  # Only for FactorExeAgent
