name: bin_pack
kwargs:
    obs_num_ems: 40
    max_num_items: 20
    max_num_ems: 40
    split_num_same_items: 2


network:
    num_transformer_layers: 2
    transformer_num_heads: 8
    transformer_key_size: 16
    transformer_mlp_units: [512]

training:
    num_epochs: 50
    num_learner_steps_per_epoch: 1
    n_steps: 30
    total_batch_size: 64

evaluation:
    eval_total_batch_size: 100
    greedy_eval_total_batch_size: 100

a2c:
    learning_rate: 1e-4
