name: bin_pack
kwargs:
    obs_num_ems: 40
    max_num_items: 15
    max_num_ems: 40
    split_num_same_items: 3


network:
    num_transformer_layers: 2
    transformer_num_heads: 8
    transformer_key_size: 16
    transformer_mlp_units: [512]
    factor_iterations: 1  # Only for FactorExeAgent, values: [1, +inf]
    factor_vocab_size: 100  # Only for FactorExeAgent, values: [1, +inf]

training:
    num_epochs: 500
    num_learner_steps_per_epoch: 100
    n_steps: 20
    total_batch_size: 512
    every_k_schedule: 2  # Only for FactorExeAgent, values: [1, +inf]

evaluation:
    eval_total_batch_size: 8192
    greedy_eval_total_batch_size: 8192

agent:
    learning_rate: 3e-4
    reinforce_loss_coeff: 1.0  # Only for FactorExeAgent, values: [0.0, +inf]
    reinforce_estimators: 8  # Only for FactorExeAgent, values: [1, +inf]
    kl_loss_which_factor: one  # Only for FactorExeAgent, values: {all, one, best}
    factors_entropy_coeff: 0.01  # Only for FactorExeAgent, values: [0.0, +inf]
    reinforce_which_factor: all  # Only for FactorExeAgent, values: {all, one, best}
